#**Task 1**

Use the Schur complement to write the nonlinear matrix constraint $𝑌 ≽ 𝐴𝑋^T𝑋𝐴 + 𝐵𝑋$ as an LMI. The matrices 𝑋 and 𝑌 are variables and matrices 𝐴 and 𝐵 are constant and symmetric.

In [ ]:
import numpy as np
import cvxpy as cp

size_x = 3

A = np.array([[1, 2, 3], [2, 4, 1], [3, 1, 1]])
B = np.array([[-2, 3, 1], [3, 1, 2], [1, 2, -4]])

X = cp.Variable((size_x, size_x), symmetric=True)
Y = cp.Variable((size_x, size_x), symmetric=True)

LMI = cp.bmat([[Y - B @ X, A.T @ X.T],
               [X @ A, np.eye(size_x)]])

constraints = [LMI >> 0.0001]
prob = cp.Problem(cp.Minimize(0), constraints=constraints)

result = prob.solve(verbose=False)

if result < 1:
    print("X:")
    print(X.value)
    print("Y:")
    print(Y.value)
else:
    print("no solution")

X:
[[1.83048804e-05 1.52627864e-05 1.81639911e-05]
 [1.52627864e-05 1.61727934e-05 1.47225601e-05]
 [1.81639911e-05 1.47225601e-05 1.75215943e-05]]
Y:
[[1.27344962e-04 1.69613101e-04 1.00769990e-04]
 [1.69613101e-04 1.91410965e-04 1.46488629e-04]
 [1.00769990e-04 1.46488629e-04 7.75265528e-05]]


#**Task 2**
In a certain design problem a symmetric and positive semidefinite matrix $\mathbf{A}$ must be expressed as a linear combination of three base matrices according to:
\begin{equation}
\mathbf{A(x)}=
x_1\begin{bmatrix} 1 & 0 &2\\0 &-1&0\\2&0&3\end{bmatrix}+x_2
\begin{bmatrix} 4 & 0 & 3\\0 & 2&1\\3&1&4\end{bmatrix}+x_3
\begin{bmatrix} 0 & 2 & 1\\2 & -3&3\\1&3&-4\end{bmatrix}
\end{equation}
The matrix $\mathbf{A}$ should be normalized in all cases so that the trace of $\mathbf{A}$ equals 1.
>Find matrix $\mathbf{A}$ with smallest maximal eigenvalue.

>Find matrix $\mathbf{A}$ with largest minimal eigenvalue.

> Find matrix $\mathbf{A}$ with minimal eigenvalue spread 𝜆𝑚𝑎𝑥(𝐴) − 𝜆𝑚𝑖𝑛(𝐴).

In [ ]:
A1 = np.array([[1, 0, 2], [0, -1, 0], [2, 0, 3]])
A2 = np.array([[4, 0, 3], [0, 2, 1], [3, 1, 4]])
A3 = np.array([[0, 2, 1], [2, -3, 3], [1, 3, -4]])

x = cp.Variable(3)
A = cp.Variable((3,3), symmetric=True)

constraints1 = [A==x[0]*A1+x[1]*A2+x[2]*A3, cp.trace(A)==1, A >> 0.000001]
prob1 = cp.Problem(cp.Minimize(cp.lambda_max(A)), constraints=constraints1)

result = prob1.solve(verbose=False)
# print(A.value)
e1, _ = np.linalg.eig(A.value)
print(e1)

[0.13071346 0.43466008 0.43462646]


In [ ]:
constraints2 = [A==x[0]*A1+x[1]*A2+x[2]*A3, cp.trace(A)==1, A >> 0.000001]
prob2 = cp.Problem(cp.Minimize(-cp.lambda_min(A)), constraints=constraints2)

result = prob2.solve(verbose=False)
print(A.value)
e2, _ = np.linalg.eig(A.value)
print(e2)

[[ 0.28539889 -0.09829878  0.02104241]
 [-0.09829878  0.46277645 -0.04732697]
 [ 0.02104241 -0.04732697  0.25182465]]
[0.51661353 0.24169291 0.24169356]


In [ ]:
constraints3 = [A==x[0]*A1+x[1]*A2+x[2]*A3, cp.trace(A)==1, A >> 0.000001]
prob3 = cp.Problem(cp.Minimize(cp.lambda_max(A)-cp.lambda_min(A)), constraints=constraints3)

result = prob3.solve(verbose=False)
print(A.value)
e3, _ = np.linalg.eig(A.value)
print(e3)

[[ 0.3093802  -0.07748647  0.08165873]
 [-0.07748647  0.40487967 -0.016558  ]
 [ 0.08165873 -0.016558    0.28574012]]
[0.46646536 0.20649927 0.32703537]
